version: '3.5'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      APP_LOG_LEVEL: DEBUG
      APP_POLICY_FILE_PATH: policy.json
      APP_SQLDB_HOST: postgres
      APP_SQLDB_PORT: 5432
      APP_SQLDB_USER: postgres
      APP_SQLDB_PASS: postgres_pass
      APP_SQLDB_DB_NAME: postgres

      TLS_HOST: 0.0.0.0
      TLS_PORT: 8080
      TLS_CERTIFICATE: ./cert/RootCA.crt
      TLS_PRIVATE_KEY: ./cert/RootCA.key
    volumes:
      - ./game/policy.json:/policy.json
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
